### Patroni yml file 
scope: postgres
namespace: /db/
name: pg_node1

restapi:
  listen: 0.0.0.0:8008
  connect_address: x.x.x.x:8008

etcd3:
  hosts: x.x.x.x:2379,x.x.x.x:2379,x.x.x.x:2379,x.x.x.x:2379
  protocol: http

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      pg_hba:
        - host replication replicator 127.0.0.1/32 trust
        - host replication replicator x.x.x.x/0 scram-sha-256
        - host replication replicator x.x.x.x/0 scram-sha-256
        - host replication replicator x.x.x.x/0 scram-sha-256
        - host replication replicator x.x.x.x/0 scram-sha-256
        - host all all 0.0.0.0/0 scram-sha-256
  initdb:
    - encoding: UTF8
    - data-checksums
  users:
    admin:
      password: admin
      options:
        - createrole
        - createdb
postgresql:
  listen: 0.0.0.0:5432
  connect_address: x.x.x.x:5432
  data_dir: /var/lib/postgresql/17/main
  bin_dir: /usr/lib/postgresql/17/bin
  pgpass: /tmp/pgpass0
  authentication:
    replication:
      username: replicator
      password: password
    superuser:
      username: postgres
      password: password
  parameters:
    unix_socket_directories: "."
tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
#### End of Patroni Yml file
